name: zebra_rfid_sdk_plugin_example
description: Demonstrates how to use the zebra_rfid_sdk_plugin plugin.

publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  zebra_rfid_sdk_plugin:
    path: ../
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

